# Generated by Django 5.2.7 on 2026-02-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('file_path', models.CharField(max_length=1024)),
                ('feature_vector', models.BinaryField()),
                ('sharpness_score', models.FloatField()),
                ('brightness_score', models.FloatField()),
                ('file_size_bytes', models.BigIntegerField()),
                ('resolution_width', models.IntegerField()),
                ('resolution_height', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classifier_data', models.BinaryField()),
                ('training_sample_count', models.IntegerField()),
                ('accuracy_score', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
