# Generated by Django 5.2.7 on 2025-10-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extract", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionjob",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
