# Generated by Django 5.2.7 on 2025-10-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extract", "0002_extractionjob_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractionjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("done", "Done"),
                    ("error", "Error"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=16,
            ),  # noqa: E501
        ),
    ]
