# Generated by Django 5.2.7 on 2025-10-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0003_alter_extractionjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('cancelling', 'Cancelling'), ('done', 'Done'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=16),  # noqa: E501
        ),
    ]
