# Generated by Django 5.2.7 on 2026-02-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0004_alter_extractionjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('deduplicating', 'Deduplicating'), ('cancelling', 'Cancelling'), ('done', 'Done'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
    ]
